### ISSUE TITLE
Install is failing

### ISSUE THREAD

**Issue by kumy** [k2bd/gh-webhooks#13]
Hi @k2bd 
I tried to install your package but it fails with
```
ImportError: cannot import name 'getargspec' from 'inspect'
```

here is the full session
```
# ~/GIT/github/gh-webhooks
$ pipenv shell --python 3.11
Creating a virtualenv for this project...
Pipfile: /home/user/GIT/github/gh-webhooks/Pipfile
Using /home/user/.pyenv/versions/3.11.6/bin/python3 (3.11.6) to create virtualenv...
⠸ Creating virtual environment...created virtual environment CPython3.11.6.final.0-64 in 200ms
  creator CPython3Posix(dest=/home/user/GIT/github/gh-webhooks/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/user/.local/share/virtualenv)
    added seed packages: pip==24.0, setuptools==69.5.1, wheel==0.43.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/user/GIT/github/gh-webhooks/.venv
Launching subshell in virtual environment...
 . /home/user/GIT/github/gh-webhooks/.venv/bin/activate

# ~/GIT/github/gh-webhooks
$  . /home/user/GIT/github/gh-webhooks/.venv/bin/activate

# ~/GIT/github/gh-webhooks
$ pip install gh_webhook
Collecting gh_webhook
  Using cached gh_webhook-0.2.tar.gz (1.6 kB)
  Preparing metadata (setup.py) ... done
Collecting bottle==0.12.10 (from gh_webhook)
  Using cached bottle-0.12.10.tar.gz (69 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8ucgwwiz/bottle_6fa12f3cde2144668f359a9e2e713491/setup.py", line 10, in <module>
          import bottle
        File "/tmp/pip-install-8ucgwwiz/bottle_6fa12f3cde2144668f359a9e2e713491/bottle.py", line 44, in <module>
          from inspect import getargspec
      ImportError: cannot import name 'getargspec' from 'inspect' (/home/user/.pyenv/versions/3.11.6/lib/python3.11/inspect.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I hope can have a look
Thanks a lot

**Comment by kumy** [comment]
It was an issue from my side `pip install gh-webhook` was missing the leading `s` :facepalm: 

```
$ pip install gh-webhooks
Collecting gh-webhooks
  Downloading gh_webhooks-0.6.0-py3-none-any.whl.metadata (3.6 kB)
Collecting pydantic==1.9.0 (from pydantic[email]==1.9.0->gh-webhooks)
  Using cached pydantic-1.9.0-py3-none-any.whl.metadata (121 kB)
Collecting stringcase<2.0.0,>=1.2.0 (from gh-webhooks)
  Using cached stringcase-1.2.0-py3-none-any.whl
Requirement already satisfied: typing-extensions<5.0.0,>=4.2.0 in ./.venv/lib/python3.11/site-packages (from gh-webhooks) (4.12.1)
Collecting email-validator>=1.0.3 (from pydantic[email]==1.9.0->gh-webhooks)
  Using cached email_validator-2.1.1-py3-none-any.whl.metadata (26 kB)
Collecting dnspython>=2.0.0 (from email-validator>=1.0.3->pydantic[email]==1.9.0->gh-webhooks)
  Using cached dnspython-2.6.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: idna>=2.0.0 in ./.venv/lib/python3.11/site-packages (from email-validator>=1.0.3->pydantic[email]==1.9.0->gh-webhooks) (3.7)
Downloading gh_webhooks-0.6.0-py3-none-any.whl (28 kB)
Using cached pydantic-1.9.0-py3-none-any.whl (140 kB)
Using cached email_validator-2.1.1-py3-none-any.whl (30 kB)
Using cached dnspython-2.6.1-py3-none-any.whl (307 kB)
Installing collected packages: stringcase, pydantic, dnspython, email-validator, gh-webhooks
Successfully installed dnspython-2.6.1 email-validator-2.1.1 gh-webhooks-0.6.0 pydantic-1.9.0 stringcase-1.2.0
```
